# Generated by Django 5.0.6 on 2024-05-22 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_employee_emp_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_employed',
            field=models.BooleanField(default=False),
        ),
    ]
