# Generated by Django 5.0.6 on 2024-05-22 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_employee_is_employed'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='joined_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
