# Generated by Django 5.0.6 on 2024-05-22 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_employee_joined_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
