# Generated by Django 5.0.6 on 2024-05-22 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_employee_emp_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_files',
            field=models.FileField(default=0, upload_to='file_uploads/'),
            preserve_default=False,
        ),
    ]
