# Generated by Django 5.0.6 on 2024-05-23 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_employee_emp_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_profile',
            field=models.ImageField(blank=True, null=True, upload_to='emp_profile_pics/'),
        ),
    ]
