# Generated by Django 5.0.6 on 2024-05-23 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_employee_emp_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
